name: Deploy ARO with Bicep Template

on: workflow_dispatch

env:
  AZURERG: POC-ARO-002
  AZURE_REGION: eastus2

jobs:

  create-azure-rg:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0 # Optional
          inlineScript: |
            az group create --location $AZURE_REGION -n $AZURERG

  deploy-bicep-template:
    if: ${{ success() }}
    needs: create-azure-rg
    runs-on: ubuntu-latest
    environment: PoC-ARO
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Deploy ARO with Bicep Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ env.AZURERG }}
        template: ./bicep/main.bicep
        parameters: ./bicep/parameters.json
        failOnStdErr: false
